-- arbiter/sql/migrations/001_execution_persistence.sql
-- Phase 2 EXEC-02: Execution state persistence for orders, fills, incidents, and top-level arbs.
-- Forward-only -- do not edit this file after it is applied to any environment.

CREATE TABLE IF NOT EXISTS execution_arbs (
    arb_id              VARCHAR(40) PRIMARY KEY,
    canonical_id        VARCHAR(60) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    net_edge            DECIMAL(8,4),
    realized_pnl        DECIMAL(10,4) DEFAULT 0,
    opportunity_json    JSONB,
    is_simulation       BOOLEAN DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    closed_at           TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_execution_arbs_canonical ON execution_arbs(canonical_id);
CREATE INDEX IF NOT EXISTS idx_execution_arbs_status ON execution_arbs(status);

CREATE TABLE IF NOT EXISTS execution_orders (
    order_id            VARCHAR(100) PRIMARY KEY,
    arb_id              VARCHAR(40) NOT NULL REFERENCES execution_arbs(arb_id),
    client_order_id     VARCHAR(100),
    platform            VARCHAR(20) NOT NULL,
    market_id           VARCHAR(100) NOT NULL,
    canonical_id        VARCHAR(60) NOT NULL,
    side                VARCHAR(4) NOT NULL,
    price               DECIMAL(8,4) NOT NULL,
    quantity            DECIMAL(12,2) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    fill_price          DECIMAL(8,4) DEFAULT 0,
    fill_qty            DECIMAL(12,2) DEFAULT 0,
    error               TEXT DEFAULT '',
    submitted_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    terminal_at         TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_execution_orders_arb ON execution_orders(arb_id);
CREATE INDEX IF NOT EXISTS idx_execution_orders_nonterminal
    ON execution_orders(status)
    WHERE status IN ('pending', 'submitted', 'partial');
CREATE INDEX IF NOT EXISTS idx_execution_orders_client_id
    ON execution_orders(client_order_id)
    WHERE client_order_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS execution_fills (
    fill_id             SERIAL PRIMARY KEY,
    order_id            VARCHAR(100) NOT NULL REFERENCES execution_orders(order_id),
    price               DECIMAL(8,4) NOT NULL,
    quantity            DECIMAL(12,2) NOT NULL,
    fees_paid           DECIMAL(10,4) DEFAULT 0,
    filled_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_execution_fills_order ON execution_fills(order_id);

CREATE TABLE IF NOT EXISTS execution_incidents (
    incident_id         VARCHAR(40) PRIMARY KEY,
    arb_id              VARCHAR(40),
    canonical_id        VARCHAR(60),
    severity            VARCHAR(20) NOT NULL,
    message             TEXT NOT NULL,
    metadata            JSONB,
    status              VARCHAR(20) DEFAULT 'open',
    resolved_at         TIMESTAMPTZ,
    resolution_note     TEXT DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_incidents_open ON execution_incidents(status) WHERE status = 'open';
CREATE INDEX IF NOT EXISTS idx_incidents_arb ON execution_incidents(arb_id);
