-- 005_unique_client_order_id.sql
-- C4.3: enforce idempotency on execution_orders.client_order_id.
--
-- Before this migration there was only a non-unique partial index on
-- execution_orders.client_order_id (idx_execution_orders_client_id, added
-- in 001). The engine's place/cancel/retry chain uses client_order_id as
-- the platform-side idempotency key, but nothing at the DB layer stopped
-- two rows from sharing one. Replacing the non-unique partial index with
-- a UNIQUE partial index turns the idempotency invariant into a hard
-- constraint: a buggy retry path that tries to insert a second row with
-- the same client_order_id will now fail loudly instead of silently
-- corrupting the audit trail.
--
-- NULLs are excluded because Polymarket orders have no client_order_id
-- concept and store NULL; many NULL rows must coexist. Postgres's WHERE
-- clause keeps the index partial so NULLs are not constrained.
--
-- Forward-only -- do not edit this file after it is applied to any env.

DROP INDEX IF EXISTS idx_execution_orders_client_id;

CREATE UNIQUE INDEX IF NOT EXISTS idx_execution_orders_client_id_unique
    ON execution_orders(client_order_id)
    WHERE client_order_id IS NOT NULL;
