-- 006_stuck_trade_tracking.sql
-- Track last-checked timestamps + recovery notes for the 5-min stuck-trade
-- reconciliation loop. Without these columns, an arb stuck in
-- recovering/pending for days has no record of when the system last asked
-- the venue what state it's in — operators couldn't tell whether the loop
-- was even running.
--
-- Forward-only -- do not edit this file after it is applied to any env.

ALTER TABLE execution_arbs
    ADD COLUMN IF NOT EXISTS last_checked_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS recovery_notes   TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_execution_arbs_nonterminal_age
    ON execution_arbs(created_at)
    WHERE status IN ('pending', 'submitted', 'recovering');
