-- 007_separate_unwind_pnl.sql
-- Split arbitrage PnL from naked-leg unwind PnL.
--
-- The 2026-05 audit found that $129.48 of $135.38 reported "profit" was
-- actually directional luck on unhedged Kalshi positions — naked-leg
-- payouts at settlement, NOT real arbitrage edge.  Only $5.90 came from
-- both-legs-filled trades.  Lumping the two together makes the
-- profitability gate read favorably while the system is, in reality,
-- not capturing arb edge at all.
--
-- This migration adds an ``unwind_pnl`` column so the two streams can be
-- reported separately.  The legacy ``realized_pnl`` column continues to
-- hold the total (arb + unwind) for backward compat with existing
-- queries; the "real arb PnL" is ``realized_pnl - unwind_pnl``.
--
-- Historical rows: unwind_pnl defaults to 0 — pre-migration trades will
-- attribute their entire realized_pnl to "arb PnL" by default.  This is
-- a known mis-attribution for the 4 weeks of prod data prior to this
-- migration; a backfill is out of scope (would require re-classifying
-- every closed arb from execution_incidents auto_unwind events).
--
-- Forward-only — do not edit this file after it is applied to any env.

ALTER TABLE execution_arbs
    ADD COLUMN IF NOT EXISTS unwind_pnl NUMERIC(10, 4) NOT NULL DEFAULT 0;
