"""
Auto-generated by scripts/discovery/bulk_discover.py
DO NOT edit manually — re-run the discovery script to regenerate.

To load into the live system:
    from data.discovered_seeds import DISCOVERED_SEEDS
    MARKET_SEEDS = MARKET_SEEDS + DISCOVERED_SEEDS
"""
from __future__ import annotations
from arbiter.config.settings import MarketMappingRecord

DISCOVERED_SEEDS = (
    MarketMappingRecord(
        canonical_id="KXBILLS_DRIVE",
        description="Will legislation that preempts state and local autonomous vehicle laws by establishing a unified federal regulatory fram",
        tags=("self",),
        kalshi="KXBILLS-DRIVE",
        polymarket="0x58d735c94571661e7819362dc457b44062b6623e8cb018bb5ca5a52bffe5f897",
        polymarket_question="Will the SELF DRIVE Act become law this year?",
        status="confirmed",
        allow_auto_trade=False,
        resolution_match_status="pending_operator_review",
        notes="Bulk-discovered 2027-01-01; similarity=0.695. Pending manual review before live trading.",
    ),
    MarketMappingRecord(
        canonical_id="KXBILLS_HOUS",
        description="Will legislation that would revise federal housing programs to increase housing supply and affordability by expanding fe",
        tags=("housing",),
        kalshi="KXBILLS-HOUS",
        polymarket="0x28d6d12eac68223138afb976332da144b44a3ebcf71960b8a0efe4f21f4521c2",
        polymarket_question="Will the Housing for the 21st Century Act become law this year?",
        status="confirmed",
        allow_auto_trade=False,
        resolution_match_status="pending_operator_review",
        notes="Bulk-discovered 2027-01-01; similarity=0.675. Pending manual review before live trading.",
    ),
)
