"""
Extended market seed records - 89 API-validated confirmed pairs.
Generated: 2026-04-22
Sources: 27 crypto/finance + 62 embedding-discovered
"""

from arbiter.mapping.store import MarketMappingRecord

MARKET_SEEDS_EXT = [
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXBTCD-26APR2207-T85799.99",
        kalshi_ticker="KXBTCD-26APR2207-T85799.99",
        polymarket_slug="will-bitcoin-have-the-best-performance-in-2026-749",
        description="Bitcoin price  on Apr 22, 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXXRP-26APR2217-T1.7799",
        kalshi_ticker="KXXRP-26APR2217-T1.7799",
        polymarket_slug="will-xrp-reach-5pt00-by-december-31-2026",
        description="Ripple price at Apr 22, 2026 at 5pm EDT?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXETH-26APR2207-T3039.99",
        kalshi_ticker="KXETH-26APR2207-T3039.99",
        polymarket_slug="eth-flipped-in-2026",
        description="Ethereum price at Apr 22, 2026 at 7am EDT?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXTSLA-26JULPROD-400000.0",
        kalshi_ticker="KXTSLA-26JULPROD-400000.0",
        polymarket_slug="will-tesla-deliver-between-375000-and-400000-vehicles-in-q2-2026",
        description="Will Tesla Inc. report above 400000 total production in Q2 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXTSLA-26JULDELIV-450000.0",
        kalshi_ticker="KXTSLA-26JULDELIV-450000.0",
        polymarket_slug="will-tesla-deliver-between-425000-and-450000-vehicles-in-q2-2026",
        description="Will Tesla Inc. report above 450000 total deliveries in Q2 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXTSLA-26JULDELIV-350000.0",
        kalshi_ticker="KXTSLA-26JULDELIV-350000.0",
        polymarket_slug="will-tesla-deliver-between-325000-and-350000-vehicles-in-q2-2026",
        description="Will Tesla Inc. report above 350000 total deliveries in Q2 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXTSLA-26JULPROD-460000.0",
        kalshi_ticker="KXTSLA-26JULPROD-460000.0",
        polymarket_slug="will-tesla-deliver-475000-or-more-vehicles-in-q2-2026",
        description="Will Tesla Inc. report above 460000 total production in Q2 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXGDP-26APR30-T3.5",
        kalshi_ticker="KXGDP-26APR30-T3.5",
        polymarket_slug="will-us-gdp-growth-in-q1-2026-be-greater-than-3pt5",
        description="Will **real GDP** increase by more than 3.5% in Q1 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-26DEC-T4.25",
        kalshi_ticker="KXFED-26DEC-T4.25",
        polymarket_slug="will-the-upper-bound-of-the-target-federal-funds-rate-be-4pt25-at-the-end-of-2026-984",
        description="Will the upper bound of the federal funds rate be above 4.25% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-26DEC-T3.75",
        kalshi_ticker="KXFED-26DEC-T3.75",
        polymarket_slug="will-the-upper-bound-of-the-target-federal-funds-rate-be-3pt75-at-the-end-of-2026-166",
        description="Will the upper bound of the federal funds rate be above 3.75% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-26DEC-T3.25",
        kalshi_ticker="KXFED-26DEC-T3.25",
        polymarket_slug="will-the-upper-bound-of-the-target-federal-funds-rate-be-3pt25-at-the-end-of-2026-282",
        description="Will the upper bound of the federal funds rate be above 3.25% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-26DEC-T2.75",
        kalshi_ticker="KXFED-26DEC-T2.75",
        polymarket_slug="will-the-upper-bound-of-the-target-federal-funds-rate-be-2pt75-at-the-end-of-2026-218",
        description="Will the upper bound of the federal funds rate be above 2.75% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXGDP-26APR30-T1.0",
        kalshi_ticker="KXGDP-26APR30-T1.0",
        polymarket_slug="will-us-gdp-growth-in-q1-2026-be-less-than-1pt0",
        description="Will **real GDP** increase by more than 1.0% in Q1 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-26DEC-T4.75",
        kalshi_ticker="KXFED-26DEC-T4.75",
        polymarket_slug="will-the-upper-bound-of-the-target-federal-funds-rate-be-4pt0-at-the-end-of-2026-386",
        description="Will the upper bound of the federal funds rate be above 4.75% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-26DEC-T3.50",
        kalshi_ticker="KXFED-26DEC-T3.50",
        polymarket_slug="will-the-upper-bound-of-the-target-federal-funds-rate-be-3pt0-at-the-end-of-2026-593",
        description="Will the upper bound of the federal funds rate be above 3.50% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXGDP-26APR30-T3.0",
        kalshi_ticker="KXGDP-26APR30-T3.0",
        polymarket_slug="will-us-gdp-growth-in-q1-2026-be-between-3pt0-and-3pt5",
        description="Will **real GDP** increase by more than 3.0% in Q1 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXGDP-26APR30-T2.0",
        kalshi_ticker="KXGDP-26APR30-T2.0",
        polymarket_slug="will-us-gdp-growth-in-q1-2026-be-between-1pt5-and-2pt0",
        description="Will **real GDP** increase by more than 2.0% in Q1 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXGDP-26JUL30-T2.5",
        kalshi_ticker="KXGDP-26JUL30-T2.5",
        polymarket_slug="will-us-gdp-growth-in-2026-be-greater-than-2pt5",
        description="Will **real GDP** increase by more than 2.5% in Q2 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXGDP-26JUL30-T1.5",
        kalshi_ticker="KXGDP-26JUL30-T1.5",
        polymarket_slug="will-us-gdp-growth-in-2026-be-between-1pt5-and-2pt0",
        description="Will **real GDP** increase by more than 1.5% in Q2 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-27APR-T4.25",
        kalshi_ticker="KXFED-27APR-T4.25",
        polymarket_slug="will-the-feds-upper-bound-reach-4pt25-or-higher-before-2027",
        description="Will the upper bound of the federal funds rate be above 4.25% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-26DEC-T5.25",
        kalshi_ticker="KXFED-26DEC-T5.25",
        polymarket_slug="fed-rate-cut-by-april-2026-meeting",
        description="Will the upper bound of the federal funds rate be above 5.25% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXGDP-26JUL30-T2.0",
        kalshi_ticker="KXGDP-26JUL30-T2.0",
        polymarket_slug="will-us-gdp-growth-in-2026-be-between-2pt0-and-2pt5",
        description="Will **real GDP** increase by more than 2.0% in Q2 2026?",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-27APR-T3.25",
        kalshi_ticker="KXFED-27APR-T3.25",
        polymarket_slug="will-the-feds-lower-bound-reach-3pt25-or-lower-before-2027-269",
        description="Will the upper bound of the federal funds rate be above 3.25% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-27APR-T2.75",
        kalshi_ticker="KXFED-27APR-T2.75",
        polymarket_slug="will-the-feds-lower-bound-reach-2pt75-or-lower-before-2027-448-727-854",
        description="Will the upper bound of the federal funds rate be above 2.75% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-27APR-T2.25",
        kalshi_ticker="KXFED-27APR-T2.25",
        polymarket_slug="will-the-feds-lower-bound-reach-2pt25-or-lower-before-2027-766-981-398-889-982",
        description="Will the upper bound of the federal funds rate be above 2.25% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-27APR-T1.75",
        kalshi_ticker="KXFED-27APR-T1.75",
        polymarket_slug="will-the-feds-lower-bound-reach-1pt75-or-lower-before-2027-123-334-678-153-953-848-473",
        description="Will the upper bound of the federal funds rate be above 1.75% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXFED-27APR-T1.25",
        kalshi_ticker="KXFED-27APR-T1.25",
        polymarket_slug="will-the-feds-lower-bound-reach-1pt25-or-lower-before-2027-683-273-676-864-498-519",
        description="Will the upper bound of the federal funds rate be above 1.25% following the Fed\",
        category="crypto",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20269BDE77599B3-97ED1BACF7A",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20269BDE77599B3-97ED1BACF7A",
        polymarket_slug="dfb-lev-bay-2026-04-22-btts",
        description="Bayer 04 Leverkusen vs. FC Bayern München: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S202614D721DC7EF-7DED97F4636",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S202614D721DC7EF-7DED97F4636",
        polymarket_slug="dfb-lev-bay-2026-04-22-btts",
        description="Bayer 04 Leverkusen vs. FC Bayern München: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026905D01BFE28-D224B7A25C9",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026905D01BFE28-D224B7A25C9",
        polymarket_slug="nba-cle-tor-2026-04-23-points-brandon-ingram-20pt5",
        description="Brandon Ingram: Points O/U 20.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026863E136B9B1-A039172FD87",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026863E136B9B1-A039172FD87",
        polymarket_slug="nba-phx-okc-2026-04-22-points-dillon-brooks-16pt5",
        description="Dillon Brooks: Points O/U 16.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026A8EF3CAE445-0A0D099706F",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026A8EF3CAE445-0A0D099706F",
        polymarket_slug="nba-cle-tor-2026-04-23-points-brandon-ingram-20pt5",
        description="Brandon Ingram: Points O/U 20.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S202626CCE6C32F2-B6CE7E7841E",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S202626CCE6C32F2-B6CE7E7841E",
        polymarket_slug="nba-cle-tor-2026-04-23-points-brandon-ingram-20pt5",
        description="Brandon Ingram: Points O/U 20.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20261977C16F5AD-F52B0D060DB",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20261977C16F5AD-F52B0D060DB",
        polymarket_slug="nba-cle-tor-2026-04-23-points-brandon-ingram-20pt5",
        description="Brandon Ingram: Points O/U 20.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S202618AC450400C-2FCC35331F2",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S202618AC450400C-2FCC35331F2",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026749AF50927C-2ED44152F0D",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026749AF50927C-2ED44152F0D",
        polymarket_slug="nba-den-min-2026-04-23-points-julius-randle-19pt5",
        description="Julius Randle: Points O/U 19.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S2026CB681029B71-6A1B672247B",
        kalshi_ticker="KXMVECROSSCATEGORY-S2026CB681029B71-6A1B672247B",
        polymarket_slug="nba-phx-okc-2026-04-22-points-jalen-williams-18pt5",
        description="Jalen Williams: Points O/U 18.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20266054DC7D6E8-283104F5212",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20266054DC7D6E8-283104F5212",
        polymarket_slug="nba-orl-det-2026-04-22-points-paolo-banchero-20pt5",
        description="Paolo Banchero: Points O/U 20.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20265B69E54A03B-F2538E5A68C",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20265B69E54A03B-F2538E5A68C",
        polymarket_slug="uwcl-bm-fcb-2026-04-25-btts",
        description="FC Bayern München vs. FC Barcelona: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S2026847CFFF0C72-F385B7569B6",
        kalshi_ticker="KXMVECROSSCATEGORY-S2026847CFFF0C72-F385B7569B6",
        polymarket_slug="nba-orl-det-2026-04-22-points-paolo-banchero-20pt5",
        description="Paolo Banchero: Points O/U 20.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20265B69E54A03B-F2538E5A68C",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20265B69E54A03B-F2538E5A68C",
        polymarket_slug="uwcl-fcb-bm-2026-05-03-btts",
        description="FC Barcelona vs. FC Bayern München: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20263801BA31191-2E4C0B3BEAF",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20263801BA31191-2E4C0B3BEAF",
        polymarket_slug="nba-orl-det-2026-04-22-points-desmond-bane-18pt5",
        description="Desmond Bane: Points O/U 18.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S2026B4B63FD0DDB-7E8BACB45DF",
        kalshi_ticker="KXMVECROSSCATEGORY-S2026B4B63FD0DDB-7E8BACB45DF",
        polymarket_slug="nba-phx-okc-2026-04-22-points-devin-booker-23pt5",
        description="Devin Booker: Points O/U 23.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S2026B046350A6CC-94CC1EB09D7",
        kalshi_ticker="KXMVECROSSCATEGORY-S2026B046350A6CC-94CC1EB09D7",
        polymarket_slug="nba-orl-det-2026-04-22-points-wendell-carter-jr-2pt5",
        description="Wendell Carter Jr.: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S20269956AECE293-D473D73DC20",
        kalshi_ticker="KXMVECROSSCATEGORY-S20269956AECE293-D473D73DC20",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S2026B9D1DFB1FC9-71F6D63C6F5",
        kalshi_ticker="KXMVECROSSCATEGORY-S2026B9D1DFB1FC9-71F6D63C6F5",
        polymarket_slug="nba-cle-tor-2026-04-23-points-james-harden-20pt5",
        description="James Harden: Points O/U 20.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20260DBC79815AC-231C5DFBE8D",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20260DBC79815AC-231C5DFBE8D",
        polymarket_slug="nba-orl-det-2026-04-22-points-cade-cunningham-28pt5",
        description="Cade Cunningham: Points O/U 28.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S20262B14F74ADD6-349F5E1D3D3",
        kalshi_ticker="KXMVECROSSCATEGORY-S20262B14F74ADD6-349F5E1D3D3",
        polymarket_slug="uwcl-bm-fcb-2026-04-25-btts",
        description="FC Bayern München vs. FC Barcelona: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026453E0448369-ECA6FADE4E1",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026453E0448369-ECA6FADE4E1",
        polymarket_slug="nba-phx-okc-2026-04-22-assists-shai-gilgeous-alexander-6pt5",
        description="Shai Gilgeous-Alexander: Assists O/U 6.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026BA0AAFBF0FC-51B818C26EB",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026BA0AAFBF0FC-51B818C26EB",
        polymarket_slug="nba-orl-det-2026-04-22-points-desmond-bane-18pt5",
        description="Desmond Bane: Points O/U 18.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S202644176CB4A9D-4858093489B",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S202644176CB4A9D-4858093489B",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S2026C653F68BF93-B3020B59F14",
        kalshi_ticker="KXMVECROSSCATEGORY-S2026C653F68BF93-B3020B59F14",
        polymarket_slug="nba-phx-okc-2026-04-22-points-jalen-williams-18pt5",
        description="Jalen Williams: Points O/U 18.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20263A6D972FC4F-536AC41C442",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20263A6D972FC4F-536AC41C442",
        polymarket_slug="nba-orl-det-2026-04-22-points-paolo-banchero-20pt5",
        description="Paolo Banchero: Points O/U 20.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S2026F05A2E5C66F-F988ADD52F0",
        kalshi_ticker="KXMVECROSSCATEGORY-S2026F05A2E5C66F-F988ADD52F0",
        polymarket_slug="nba-phx-okc-2026-04-22-points-dillon-brooks-16pt5",
        description="Dillon Brooks: Points O/U 16.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026E7119343632-CAED56F7488",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026E7119343632-CAED56F7488",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026F9E341EC254-69428E9AECD",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026F9E341EC254-69428E9AECD",
        polymarket_slug="nba-orl-det-2026-04-22-points-desmond-bane-18pt5",
        description="Desmond Bane: Points O/U 18.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20269ED48A5BE2D-471BCA6F931",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20269ED48A5BE2D-471BCA6F931",
        polymarket_slug="nba-orl-det-2026-04-22-points-paolo-banchero-20pt5",
        description="Paolo Banchero: Points O/U 20.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026DC99B6AF4F4-F237708A7EB",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026DC99B6AF4F4-F237708A7EB",
        polymarket_slug="nba-orl-det-2026-04-22-points-cade-cunningham-28pt5",
        description="Cade Cunningham: Points O/U 28.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S202673FB91AD7F5-EAD5586E992",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S202673FB91AD7F5-EAD5586E992",
        polymarket_slug="nba-orl-det-2026-04-22-points-desmond-bane-18pt5",
        description="Desmond Bane: Points O/U 18.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20261791DE0E8D2-F38934455D5",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20261791DE0E8D2-F38934455D5",
        polymarket_slug="nba-orl-det-2026-04-22-points-cade-cunningham-28pt5",
        description="Cade Cunningham: Points O/U 28.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026453E0448369-ECA6FADE4E1",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026453E0448369-ECA6FADE4E1",
        polymarket_slug="nba-phx-okc-2026-04-22-points-shai-gilgeous-alexander-29pt5",
        description="Shai Gilgeous-Alexander: Points O/U 29.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S2026F01756BCC30-096678D8592",
        kalshi_ticker="KXMVECROSSCATEGORY-S2026F01756BCC30-096678D8592",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S202618305729348-F344D1BD56F",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S202618305729348-F344D1BD56F",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026932ED2DCF9C-93943ACC856",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026932ED2DCF9C-93943ACC856",
        polymarket_slug="nba-orl-det-2026-04-22-points-wendell-carter-jr-2pt5",
        description="Wendell Carter Jr.: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S202604A242944AD-76BFDCAF3EF",
        kalshi_ticker="KXMVECROSSCATEGORY-S202604A242944AD-76BFDCAF3EF",
        polymarket_slug="nba-orl-det-2026-04-22-points-paolo-banchero-20pt5",
        description="Paolo Banchero: Points O/U 20.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S20262B14F74ADD6-349F5E1D3D3",
        kalshi_ticker="KXMVECROSSCATEGORY-S20262B14F74ADD6-349F5E1D3D3",
        polymarket_slug="uwcl-fcb-bm-2026-05-03-btts",
        description="FC Barcelona vs. FC Bayern München: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S202660AAAE6D640-8558D40A629",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S202660AAAE6D640-8558D40A629",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S20267D7B2B0AFD0-C53C87C9AA6",
        kalshi_ticker="KXMVECROSSCATEGORY-S20267D7B2B0AFD0-C53C87C9AA6",
        polymarket_slug="nba-phx-okc-2026-04-22-points-devin-booker-23pt5",
        description="Devin Booker: Points O/U 23.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S202651CB98BA02E-64C9CEAE814",
        kalshi_ticker="KXMVECROSSCATEGORY-S202651CB98BA02E-64C9CEAE814",
        polymarket_slug="nba-phx-okc-2026-04-22-points-shai-gilgeous-alexander-29pt5",
        description="Shai Gilgeous-Alexander: Points O/U 29.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S20260C79896C7F6-774F06F8973",
        kalshi_ticker="KXMVECROSSCATEGORY-S20260C79896C7F6-774F06F8973",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026081745E26FC-3C0654CA55B",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026081745E26FC-3C0654CA55B",
        polymarket_slug="uwcl-bm-fcb-2026-04-25-btts",
        description="FC Bayern München vs. FC Barcelona: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026EBB293BFAED-1DFAF70A38F",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026EBB293BFAED-1DFAF70A38F",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026BCEA47ADB1D-888DD64E057",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026BCEA47ADB1D-888DD64E057",
        polymarket_slug="2026-soccer-liga-mx-winner-atltico-de-san-luis",
        description="Will Atlético de San Luis win Liga MX?",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S2026242D8A0F70D-31BA3DE4028",
        kalshi_ticker="KXMVECROSSCATEGORY-S2026242D8A0F70D-31BA3DE4028",
        polymarket_slug="nba-orl-det-2026-04-22-points-franz-wagner-17pt5",
        description="Franz Wagner: Points O/U 17.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20269BDE77599B3-97ED1BACF7A",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20269BDE77599B3-97ED1BACF7A",
        polymarket_slug="dfb-lev-bay-2026-04-22-draw",
        description="Will Bayer 04 Leverkusen vs. FC Bayern München end in a draw?",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026BCEA47ADB1D-888DD64E057",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026BCEA47ADB1D-888DD64E057",
        polymarket_slug="mex-asl-san-2026-04-22-asl",
        description="Will Atlético San Luis win on 2026-04-22?",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026881D8906EF3-9260921E59D",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026881D8906EF3-9260921E59D",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20264F7C4CD177D-F5AF957B8A3",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20264F7C4CD177D-F5AF957B8A3",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20269BDE77599B3-97ED1BACF7A",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20269BDE77599B3-97ED1BACF7A",
        polymarket_slug="bun-koe-b04-2026-04-25-btts",
        description="1. FC Köln vs. Bayer 04 Leverkusen: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026BCEA47ADB1D-888DD64E057",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026BCEA47ADB1D-888DD64E057",
        polymarket_slug="mex-jua-asl-2026-04-25-asl",
        description="Will Atlético San Luis win on 2026-04-25?",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20260E218F54B09-2327E9117B9",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20260E218F54B09-2327E9117B9",
        polymarket_slug="lal-elc-mad-2026-04-22-btts",
        description="Elche CF vs. Club Atlético de Madrid: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S20265C7FBBA71EC-B9B36D6C607",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S20265C7FBBA71EC-B9B36D6C607",
        polymarket_slug="nba-phx-okc-2026-04-22-assists-shai-gilgeous-alexander-6pt5",
        description="Shai Gilgeous-Alexander: Assists O/U 6.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026868EE3DD3E1-6DBEBFF286C",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026868EE3DD3E1-6DBEBFF286C",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026081745E26FC-3C0654CA55B",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026081745E26FC-3C0654CA55B",
        polymarket_slug="uwcl-fcb-bm-2026-05-03-btts",
        description="FC Barcelona vs. FC Bayern München: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S202614D721DC7EF-7DED97F4636",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S202614D721DC7EF-7DED97F4636",
        polymarket_slug="bun-koe-b04-2026-04-25-btts",
        description="1. FC Köln vs. Bayer 04 Leverkusen: Both Teams to Score",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026A39C908BCEE-6B47BA1E2C9",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026A39C908BCEE-6B47BA1E2C9",
        polymarket_slug="nba-orl-det-2026-04-22-points-tobias-harris-14pt5",
        description="Tobias Harris: Points O/U 14.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026F27310D1E28-53CA86EF0B5",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026F27310D1E28-53CA86EF0B5",
        polymarket_slug="nba-orl-det-2026-04-22-points-duncan-robinson-2pt5",
        description="Duncan Robinson: Points O/U 2.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVESPORTSMULTIGAMEEXTENDED-S2026F3F82C891D2-46818BA7219",
        kalshi_ticker="KXMVESPORTSMULTIGAMEEXTENDED-S2026F3F82C891D2-46818BA7219",
        polymarket_slug="nba-phx-okc-2026-04-22-assists-shai-gilgeous-alexander-6pt5",
        description="Shai Gilgeous-Alexander: Assists O/U 6.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
    MarketMappingRecord(
        canonical_id="CONFIRMED_KXMVECROSSCATEGORY-S202645FF98C4C52-6CE8F5F9F0F",
        kalshi_ticker="KXMVECROSSCATEGORY-S202645FF98C4C52-6CE8F5F9F0F",
        polymarket_slug="nba-orl-det-2026-04-22-points-franz-wagner-17pt5",
        description="Franz Wagner: Points O/U 17.5",
        category="embeddings",
        status="confirmed",
        allow_auto_trade=True,
    ),
]
