"""
Extended market seed records — crypto/finance discovery.
Generated: 2026-04-22
Source: /tmp/discovered_markets_filtered.json
Kalshi relevant markets scanned: 4413
Polymarket relevant markets scanned: 19646
Total matches: 27

  crypto: 3 matches
  economics: 20 matches
  finance: 4 matches

All records have status="candidate" and allow_auto_trade=False.
Operator must review each record before enabling live trading.
"""
from __future__ import annotations

from typing import Tuple

from arbiter.config.settings import MarketMappingRecord


# 27 auto-discovered crypto/finance market mappings
CRYPTO_FINANCE_SEEDS: Tuple[MarketMappingRecord, ...] = (
    # ── CRYPTO (3 markets) ──────────────────────────────────────
    MarketMappingRecord(
        canonical_id='CRYPT_D_26APR2207_T85799_99',
        description='Bitcoin price  on Apr 22, 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('bitcoin price on apr 22 2026', 'will bitcoin have the best performance in 2026'),
        tags=('crypto', 'bitcoin'),
        kalshi='KXBTCD-26APR2207-T85799.99',
        polymarket='will-bitcoin-have-the-best-performance-in-2026-749',
        polymarket_question='Will Bitcoin have the best performance in 2026?',
        notes='Auto-discovered score=0.457. Kalshi expiry: 2026-04-29. Polymarket expiry: 2026-12-31. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Coinmarketcap / major exchange OHLCV', 'rule': 'Bitcoin price  on Apr 22, 2026?', 'settlement_date': '2026-04-29'}, 'polymarket': {'source': 'Coinmarketcap / major exchange OHLCV', 'rule': 'Will Bitcoin have the best performance in 2026?', 'settlement_date': '2026-12-31'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.457. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='CRYPT_XRP_26APR2217_T1_7799',
        description='Ripple price at Apr 22, 2026 at 5pm EDT?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('ripple price at apr 22 2026 at 5pm edt', 'will xrp reach 5 00 by december 31 2026'),
        tags=('crypto', 'ripple'),
        kalshi='KXXRP-26APR2217-T1.7799',
        polymarket='will-xrp-reach-5pt00-by-december-31-2026',
        polymarket_question='Will XRP reach $5.00 by December 31, 2026?',
        notes='Auto-discovered score=0.400. Kalshi expiry: 2026-04-29. Polymarket expiry: 2027-01-01. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Coinmarketcap / major exchange OHLCV', 'rule': 'Ripple price at Apr 22, 2026 at 5pm EDT?', 'settlement_date': '2026-04-29'}, 'polymarket': {'source': 'Coinmarketcap / major exchange OHLCV', 'rule': 'Will XRP reach $5.00 by December 31, 2026?', 'settlement_date': '2027-01-01'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.400. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='CRYPT_26APR2207_T3039_99',
        description='Ethereum price at Apr 22, 2026 at 7am EDT?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('ethereum price at apr 22 2026 at 7am edt', 'ethereum flipped in 2026'),
        tags=('crypto', 'ethereum'),
        kalshi='KXETH-26APR2207-T3039.99',
        polymarket='eth-flipped-in-2026',
        polymarket_question='Ethereum flipped in 2026?',
        notes='Auto-discovered score=0.356. Kalshi expiry: 2026-04-29. Polymarket expiry: 2027-01-01. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Coinmarketcap / major exchange OHLCV', 'rule': 'Ethereum price at Apr 22, 2026 at 7am EDT?', 'settlement_date': '2026-04-29'}, 'polymarket': {'source': 'Coinmarketcap / major exchange OHLCV', 'rule': 'Ethereum flipped in 2026?', 'settlement_date': '2027-01-01'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.356. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    # ── FINANCE (4 markets) ──────────────────────────────────────
    MarketMappingRecord(
        canonical_id='FINAN_TSLA_26JULPROD_400000_0',
        description='Will Tesla Inc. report above 400000 total production in Q2 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will tesla inc report above 400000 total production in q2 2026', 'will tesla deliver between 375000 and 400000 vehicles in q2 2026'),
        tags=('finance', 'tesla'),
        kalshi='KXTSLA-26JULPROD-400000.0',
        polymarket='will-tesla-deliver-between-375000-and-400000-vehicles-in-q2-2026',
        polymarket_question='Will Tesla deliver between 375000 and 400000 vehicles in Q2 2026',
        notes='Auto-discovered score=0.615. Kalshi expiry: 2026-08-21. Polymarket expiry: 2026-06-30. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Market operator / exchange data', 'rule': 'Will Tesla Inc. report above 400000 total production in Q2 2026?', 'settlement_date': '2026-08-21'}, 'polymarket': {'source': 'Market operator / exchange data', 'rule': 'Will Tesla deliver between 375000 and 400000 vehicles in Q2 2026', 'settlement_date': '2026-06-30'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.615. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='FINAN_TSLA_26JULDELIV_450000_0',
        description='Will Tesla Inc. report above 450000 total deliveries in Q2 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will tesla inc report above 450000 total deliveries in q2 2026', 'will tesla deliver between 425000 and 450000 vehicles in q2 2026'),
        tags=('finance', 'tesla'),
        kalshi='KXTSLA-26JULDELIV-450000.0',
        polymarket='will-tesla-deliver-between-425000-and-450000-vehicles-in-q2-2026',
        polymarket_question='Will Tesla deliver between 425000 and 450000 vehicles in Q2 2026',
        notes='Auto-discovered score=0.615. Kalshi expiry: 2026-08-21. Polymarket expiry: 2026-06-30. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Market operator / exchange data', 'rule': 'Will Tesla Inc. report above 450000 total deliveries in Q2 2026?', 'settlement_date': '2026-08-21'}, 'polymarket': {'source': 'Market operator / exchange data', 'rule': 'Will Tesla deliver between 425000 and 450000 vehicles in Q2 2026', 'settlement_date': '2026-06-30'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.615. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='FINAN_TSLA_26JULDELIV_350000_0',
        description='Will Tesla Inc. report above 350000 total deliveries in Q2 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will tesla inc report above 350000 total deliveries in q2 2026', 'will tesla deliver between 325000 and 350000 vehicles in q2 2026'),
        tags=('finance', 'tesla'),
        kalshi='KXTSLA-26JULDELIV-350000.0',
        polymarket='will-tesla-deliver-between-325000-and-350000-vehicles-in-q2-2026',
        polymarket_question='Will Tesla deliver between 325000 and 350000 vehicles in Q2 2026',
        notes='Auto-discovered score=0.615. Kalshi expiry: 2026-08-21. Polymarket expiry: 2026-06-30. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Market operator / exchange data', 'rule': 'Will Tesla Inc. report above 350000 total deliveries in Q2 2026?', 'settlement_date': '2026-08-21'}, 'polymarket': {'source': 'Market operator / exchange data', 'rule': 'Will Tesla deliver between 325000 and 350000 vehicles in Q2 2026', 'settlement_date': '2026-06-30'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.615. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='FINAN_TSLA_26JULPROD_460000_0',
        description='Will Tesla Inc. report above 460000 total production in Q2 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will tesla inc report above 460000 total production in q2 2026', 'will tesla deliver 475000 or more vehicles in q2 2026'),
        tags=('finance', 'tesla'),
        kalshi='KXTSLA-26JULPROD-460000.0',
        polymarket='will-tesla-deliver-475000-or-more-vehicles-in-q2-2026',
        polymarket_question='Will Tesla deliver 475000 or more vehicles in Q2 2026',
        notes='Auto-discovered score=0.492. Kalshi expiry: 2026-08-21. Polymarket expiry: 2026-06-30. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Market operator / exchange data', 'rule': 'Will Tesla Inc. report above 460000 total production in Q2 2026?', 'settlement_date': '2026-08-21'}, 'polymarket': {'source': 'Market operator / exchange data', 'rule': 'Will Tesla deliver 475000 or more vehicles in Q2 2026', 'settlement_date': '2026-06-30'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.492. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    # ── ECONOMICS (20 markets) ──────────────────────────────────────
    MarketMappingRecord(
        canonical_id='ECONO_GDP_26APR30_T3_5',
        description='Will **real GDP** increase by more than 3.5% in Q1 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will real gdp increase by more than 3 5 in q1 2026', 'will us gdp growth in q1 2026 be greater than 3 5'),
        tags=('economics',),
        kalshi='KXGDP-26APR30-T3.5',
        polymarket='will-us-gdp-growth-in-q1-2026-be-greater-than-3pt5',
        polymarket_question='Will US GDP growth in Q1 2026 be greater than 3.5%?',
        notes='Auto-discovered score=0.862. Kalshi expiry: 2026-07-30. Polymarket expiry: 2026-04-30. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Bureau of Economic Analysis', 'rule': 'Will **real GDP** increase by more than 3.5% in Q1 2026?', 'settlement_date': '2026-07-30'}, 'polymarket': {'source': 'Bureau of Economic Analysis', 'rule': 'Will US GDP growth in Q1 2026 be greater than 3.5%?', 'settlement_date': '2026-04-30'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.862. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_26DEC_T4_25',
        description='Will the upper bound of the federal funds rate be above 4.25% following the Fed\'s Dec 9, 2026 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 4 25 following the fed s dec 9 2026 meeting', 'will the upper bound of the target federal funds rate be 4 25 at the end of 2026'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-26DEC-T4.25',
        polymarket='will-the-upper-bound-of-the-target-federal-funds-rate-be-4pt25-at-the-end-of-2026-984',
        polymarket_question='Will the upper bound of the target federal funds rate be 4.25% at the end of 2026?',
        notes='Auto-discovered score=0.853. Kalshi expiry: 2026-12-16. Polymarket expiry: 2026-12-09. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 4.25% following the Fed's Dec 9, 2026 meeting?", 'settlement_date': '2026-12-16'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the upper bound of the target federal funds rate be 4.25% at the end of 2026?', 'settlement_date': '2026-12-09'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.853. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_26DEC_T3_75',
        description='Will the upper bound of the federal funds rate be above 3.75% following the Fed\'s Dec 9, 2026 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 3 75 following the fed s dec 9 2026 meeting', 'will the upper bound of the target federal funds rate be 3 75 at the end of 2026'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-26DEC-T3.75',
        polymarket='will-the-upper-bound-of-the-target-federal-funds-rate-be-3pt75-at-the-end-of-2026-166',
        polymarket_question='Will the upper bound of the target federal funds rate be 3.75% at the end of 2026?',
        notes='Auto-discovered score=0.853. Kalshi expiry: 2026-12-16. Polymarket expiry: 2026-12-09. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 3.75% following the Fed's Dec 9, 2026 meeting?", 'settlement_date': '2026-12-16'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the upper bound of the target federal funds rate be 3.75% at the end of 2026?', 'settlement_date': '2026-12-09'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.853. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_26DEC_T3_25',
        description='Will the upper bound of the federal funds rate be above 3.25% following the Fed\'s Dec 9, 2026 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 3 25 following the fed s dec 9 2026 meeting', 'will the upper bound of the target federal funds rate be 3 25 at the end of 2026'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-26DEC-T3.25',
        polymarket='will-the-upper-bound-of-the-target-federal-funds-rate-be-3pt25-at-the-end-of-2026-282',
        polymarket_question='Will the upper bound of the target federal funds rate be 3.25% at the end of 2026?',
        notes='Auto-discovered score=0.853. Kalshi expiry: 2026-12-16. Polymarket expiry: 2026-12-09. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 3.25% following the Fed's Dec 9, 2026 meeting?", 'settlement_date': '2026-12-16'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the upper bound of the target federal funds rate be 3.25% at the end of 2026?', 'settlement_date': '2026-12-09'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.853. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_26DEC_T2_75',
        description='Will the upper bound of the federal funds rate be above 2.75% following the Fed\'s Dec 9, 2026 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 2 75 following the fed s dec 9 2026 meeting', 'will the upper bound of the target federal funds rate be 2 75 at the end of 2026'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-26DEC-T2.75',
        polymarket='will-the-upper-bound-of-the-target-federal-funds-rate-be-2pt75-at-the-end-of-2026-218',
        polymarket_question='Will the upper bound of the target federal funds rate be 2.75% at the end of 2026?',
        notes='Auto-discovered score=0.853. Kalshi expiry: 2026-12-16. Polymarket expiry: 2026-12-09. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 2.75% following the Fed's Dec 9, 2026 meeting?", 'settlement_date': '2026-12-16'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the upper bound of the target federal funds rate be 2.75% at the end of 2026?', 'settlement_date': '2026-12-09'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.853. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_GDP_26APR30_T1_0',
        description='Will **real GDP** increase by more than 1.0% in Q1 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will real gdp increase by more than 1 0 in q1 2026', 'will us gdp growth in q1 2026 be less than 1 0'),
        tags=('economics',),
        kalshi='KXGDP-26APR30-T1.0',
        polymarket='will-us-gdp-growth-in-q1-2026-be-less-than-1pt0',
        polymarket_question='Will US GDP growth in Q1 2026 be less than 1.0%?',
        notes='Auto-discovered score=0.800. Kalshi expiry: 2026-07-30. Polymarket expiry: 2026-04-30. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Bureau of Economic Analysis', 'rule': 'Will **real GDP** increase by more than 1.0% in Q1 2026?', 'settlement_date': '2026-07-30'}, 'polymarket': {'source': 'Bureau of Economic Analysis', 'rule': 'Will US GDP growth in Q1 2026 be less than 1.0%?', 'settlement_date': '2026-04-30'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.800. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_26DEC_T4_75',
        description='Will the upper bound of the federal funds rate be above 4.75% following the Fed\'s Dec 9, 2026 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 4 75 following the fed s dec 9 2026 meeting', 'will the upper bound of the target federal funds rate be 4 0 at the end of 2026'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-26DEC-T4.75',
        polymarket='will-the-upper-bound-of-the-target-federal-funds-rate-be-4pt0-at-the-end-of-2026-386',
        polymarket_question='Will the upper bound of the target federal funds rate be 4.0% at the end of 2026?',
        notes='Auto-discovered score=0.700. Kalshi expiry: 2026-12-16. Polymarket expiry: 2026-12-09. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 4.75% following the Fed's Dec 9, 2026 meeting?", 'settlement_date': '2026-12-16'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the upper bound of the target federal funds rate be 4.0% at the end of 2026?', 'settlement_date': '2026-12-09'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.700. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_26DEC_T3_50',
        description='Will the upper bound of the federal funds rate be above 3.50% following the Fed\'s Dec 9, 2026 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 3 50 following the fed s dec 9 2026 meeting', 'will the upper bound of the target federal funds rate be 3 0 at the end of 2026'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-26DEC-T3.50',
        polymarket='will-the-upper-bound-of-the-target-federal-funds-rate-be-3pt0-at-the-end-of-2026-593',
        polymarket_question='Will the upper bound of the target federal funds rate be 3.0% at the end of 2026?',
        notes='Auto-discovered score=0.700. Kalshi expiry: 2026-12-16. Polymarket expiry: 2026-12-09. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 3.50% following the Fed's Dec 9, 2026 meeting?", 'settlement_date': '2026-12-16'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the upper bound of the target federal funds rate be 3.0% at the end of 2026?', 'settlement_date': '2026-12-09'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.700. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_GDP_26APR30_T3_0',
        description='Will **real GDP** increase by more than 3.0% in Q1 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will real gdp increase by more than 3 0 in q1 2026', 'will us gdp growth in q1 2026 be between 3 0 and 3 5'),
        tags=('economics',),
        kalshi='KXGDP-26APR30-T3.0',
        polymarket='will-us-gdp-growth-in-q1-2026-be-between-3pt0-and-3pt5',
        polymarket_question='Will US GDP growth in Q1 2026 be between 3.0% and 3.5%?',
        notes='Auto-discovered score=0.686. Kalshi expiry: 2026-07-30. Polymarket expiry: 2026-04-30. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Bureau of Economic Analysis', 'rule': 'Will **real GDP** increase by more than 3.0% in Q1 2026?', 'settlement_date': '2026-07-30'}, 'polymarket': {'source': 'Bureau of Economic Analysis', 'rule': 'Will US GDP growth in Q1 2026 be between 3.0% and 3.5%?', 'settlement_date': '2026-04-30'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.686. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_GDP_26APR30_T2_0',
        description='Will **real GDP** increase by more than 2.0% in Q1 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will real gdp increase by more than 2 0 in q1 2026', 'will us gdp growth in q1 2026 be between 1 5 and 2 0'),
        tags=('economics',),
        kalshi='KXGDP-26APR30-T2.0',
        polymarket='will-us-gdp-growth-in-q1-2026-be-between-1pt5-and-2pt0',
        polymarket_question='Will US GDP growth in Q1 2026 be between 1.5% and 2.0%?',
        notes='Auto-discovered score=0.686. Kalshi expiry: 2026-07-30. Polymarket expiry: 2026-04-30. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Bureau of Economic Analysis', 'rule': 'Will **real GDP** increase by more than 2.0% in Q1 2026?', 'settlement_date': '2026-07-30'}, 'polymarket': {'source': 'Bureau of Economic Analysis', 'rule': 'Will US GDP growth in Q1 2026 be between 1.5% and 2.0%?', 'settlement_date': '2026-04-30'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.686. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_GDP_26JUL30_T2_5',
        description='Will **real GDP** increase by more than 2.5% in Q2 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will real gdp increase by more than 2 5 in q2 2026', 'will us gdp growth in 2026 be greater than 2 5'),
        tags=('economics',),
        kalshi='KXGDP-26JUL30-T2.5',
        polymarket='will-us-gdp-growth-in-2026-be-greater-than-2pt5',
        polymarket_question='Will US GDP growth in 2026 be greater than 2.5%?',
        notes='Auto-discovered score=0.667. Kalshi expiry: 2026-10-29. Polymarket expiry: 2027-01-29. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Bureau of Economic Analysis', 'rule': 'Will **real GDP** increase by more than 2.5% in Q2 2026?', 'settlement_date': '2026-10-29'}, 'polymarket': {'source': 'Bureau of Economic Analysis', 'rule': 'Will US GDP growth in 2026 be greater than 2.5%?', 'settlement_date': '2027-01-29'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.667. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_GDP_26JUL30_T1_5',
        description='Will **real GDP** increase by more than 1.5% in Q2 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will real gdp increase by more than 1 5 in q2 2026', 'will us gdp growth in 2026 be between 1 5 and 2 0'),
        tags=('economics',),
        kalshi='KXGDP-26JUL30-T1.5',
        polymarket='will-us-gdp-growth-in-2026-be-between-1pt5-and-2pt0',
        polymarket_question='Will US GDP growth in 2026 be between 1.5% and 2.0%?',
        notes='Auto-discovered score=0.571. Kalshi expiry: 2026-10-29. Polymarket expiry: 2027-01-29. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Bureau of Economic Analysis', 'rule': 'Will **real GDP** increase by more than 1.5% in Q2 2026?', 'settlement_date': '2026-10-29'}, 'polymarket': {'source': 'Bureau of Economic Analysis', 'rule': 'Will US GDP growth in 2026 be between 1.5% and 2.0%?', 'settlement_date': '2027-01-29'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.571. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_27APR_T4_25',
        description='Will the upper bound of the federal funds rate be above 4.25% following the Fed\'s Apr 28, 2027 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 4 25 following the fed s apr 28 2027 meeting', 'will the fed s upper bound reach 4 25 or higher before 2027'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-27APR-T4.25',
        polymarket='will-the-feds-upper-bound-reach-4pt25-or-higher-before-2027',
        polymarket_question='Will the Fed’s upper bound reach 4.25% or higher before 2027?',
        notes='Auto-discovered score=0.565. Kalshi expiry: 2027-05-05. Polymarket expiry: 2026-12-31. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 4.25% following the Fed's Apr 28, 2027 meeting?", 'settlement_date': '2027-05-05'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the Fed’s upper bound reach 4.25% or higher before 2027?', 'settlement_date': '2026-12-31'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.565. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_26DEC_T5_25',
        description='Will the upper bound of the federal funds rate be above 5.25% following the Fed\'s Dec 9, 2026 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 5 25 following the fed s dec 9 2026 meeting', 'fed rate cut by april 2026 meeting'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-26DEC-T5.25',
        polymarket='fed-rate-cut-by-april-2026-meeting',
        polymarket_question='Fed rate cut by April 2026 meeting?',
        notes='Auto-discovered score=0.500. Kalshi expiry: 2026-12-16. Polymarket expiry: 2026-04-29. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 5.25% following the Fed's Dec 9, 2026 meeting?", 'settlement_date': '2026-12-16'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Fed rate cut by April 2026 meeting?', 'settlement_date': '2026-04-29'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.500. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_GDP_26JUL30_T2_0',
        description='Will **real GDP** increase by more than 2.0% in Q2 2026?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will real gdp increase by more than 2 0 in q2 2026', 'will us gdp growth in 2026 be between 2 0 and 2 5'),
        tags=('economics',),
        kalshi='KXGDP-26JUL30-T2.0',
        polymarket='will-us-gdp-growth-in-2026-be-between-2pt0-and-2pt5',
        polymarket_question='Will US GDP growth in 2026 be between 2.0% and 2.5%?',
        notes='Auto-discovered score=0.492. Kalshi expiry: 2026-10-29. Polymarket expiry: 2027-01-29. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Bureau of Economic Analysis', 'rule': 'Will **real GDP** increase by more than 2.0% in Q2 2026?', 'settlement_date': '2026-10-29'}, 'polymarket': {'source': 'Bureau of Economic Analysis', 'rule': 'Will US GDP growth in 2026 be between 2.0% and 2.5%?', 'settlement_date': '2027-01-29'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.492. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_27APR_T3_25',
        description='Will the upper bound of the federal funds rate be above 3.25% following the Fed\'s Apr 28, 2027 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 3 25 following the fed s apr 28 2027 meeting', 'will the fed s lower bound reach 3 25 or lower before 2027'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-27APR-T3.25',
        polymarket='will-the-feds-lower-bound-reach-3pt25-or-lower-before-2027-269',
        polymarket_question='Will the Fed’s lower bound reach 3.25% or lower before 2027?',
        notes='Auto-discovered score=0.471. Kalshi expiry: 2027-05-05. Polymarket expiry: 2026-12-31. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 3.25% following the Fed's Apr 28, 2027 meeting?", 'settlement_date': '2027-05-05'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the Fed’s lower bound reach 3.25% or lower before 2027?', 'settlement_date': '2026-12-31'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.471. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_27APR_T2_75',
        description='Will the upper bound of the federal funds rate be above 2.75% following the Fed\'s Apr 28, 2027 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 2 75 following the fed s apr 28 2027 meeting', 'will the fed s lower bound reach 2 75 or lower before 2027'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-27APR-T2.75',
        polymarket='will-the-feds-lower-bound-reach-2pt75-or-lower-before-2027-448-727-854',
        polymarket_question='Will the Fed’s lower bound reach 2.75% or lower before 2027?',
        notes='Auto-discovered score=0.471. Kalshi expiry: 2027-05-05. Polymarket expiry: 2026-12-31. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 2.75% following the Fed's Apr 28, 2027 meeting?", 'settlement_date': '2027-05-05'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the Fed’s lower bound reach 2.75% or lower before 2027?', 'settlement_date': '2026-12-31'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.471. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_27APR_T2_25',
        description='Will the upper bound of the federal funds rate be above 2.25% following the Fed\'s Apr 28, 2027 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 2 25 following the fed s apr 28 2027 meeting', 'will the fed s lower bound reach 2 25 or lower before 2027'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-27APR-T2.25',
        polymarket='will-the-feds-lower-bound-reach-2pt25-or-lower-before-2027-766-981-398-889-982',
        polymarket_question='Will the Fed’s lower bound reach 2.25% or lower before 2027?',
        notes='Auto-discovered score=0.471. Kalshi expiry: 2027-05-05. Polymarket expiry: 2026-12-31. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 2.25% following the Fed's Apr 28, 2027 meeting?", 'settlement_date': '2027-05-05'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the Fed’s lower bound reach 2.25% or lower before 2027?', 'settlement_date': '2026-12-31'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.471. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_27APR_T1_75',
        description='Will the upper bound of the federal funds rate be above 1.75% following the Fed\'s Apr 28, 2027 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 1 75 following the fed s apr 28 2027 meeting', 'will the fed s lower bound reach 1 75 or lower before 2027'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-27APR-T1.75',
        polymarket='will-the-feds-lower-bound-reach-1pt75-or-lower-before-2027-123-334-678-153-953-848-473',
        polymarket_question='Will the Fed’s lower bound reach 1.75% or lower before 2027?',
        notes='Auto-discovered score=0.471. Kalshi expiry: 2027-05-05. Polymarket expiry: 2026-12-31. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 1.75% following the Fed's Apr 28, 2027 meeting?", 'settlement_date': '2027-05-05'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the Fed’s lower bound reach 1.75% or lower before 2027?', 'settlement_date': '2026-12-31'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.471. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

    MarketMappingRecord(
        canonical_id='ECONO_FED_27APR_T1_25',
        description='Will the upper bound of the federal funds rate be above 1.25% following the Fed\'s Apr 28, 2027 meeting?',
        status='candidate',
        allow_auto_trade=False,
        aliases=('will the upper bound of the federal funds rate be above 1 25 following the fed s apr 28 2027 meeting', 'will the fed s lower bound reach 1 25 or lower before 2027'),
        tags=('economics', 'federal_reserve'),
        kalshi='KXFED-27APR-T1.25',
        polymarket='will-the-feds-lower-bound-reach-1pt25-or-lower-before-2027-683-273-676-864-498-519',
        polymarket_question='Will the Fed’s lower bound reach 1.25% or lower before 2027?',
        notes='Auto-discovered score=0.471. Kalshi expiry: 2027-05-05. Polymarket expiry: 2026-12-31. Status: candidate — operator review required before live trading.',
        resolution_criteria={'kalshi': {'source': 'Federal Reserve', 'rule': "Will the upper bound of the federal funds rate be above 1.25% following the Fed's Apr 28, 2027 meeting?", 'settlement_date': '2027-05-05'}, 'polymarket': {'source': 'Federal Reserve', 'rule': 'Will the Fed’s lower bound reach 1.25% or lower before 2027?', 'settlement_date': '2026-12-31'}, 'criteria_match': 'similar', 'operator_note': 'Auto-discovered 2026-04-22, score=0.471. Needs operator review before live trading.'},
        resolution_match_status='similar',
    ),

)
