"""Canonical aliases for teams/entities used in market mapping.

The mapping layer uses these codes as structural identifiers.  Keep aliases
conservative: an alias should only collapse when the two codes truly refer to
the same team/entity in the relevant venue feeds.
"""
from __future__ import annotations

TEAM_ALIASES: dict[str, str] = {
    # Draw/tie outcomes.
    "draw": "tie",
    "tie": "tie",
    # MLS.
    "atx": "aus",
    "aus": "aus",
    "atl": "atl",
    "chi": "chi",
    "clb": "clb",
    "cin": "cin",
    "col": "col",
    "dal": "dal",
    "dc": "dc",
    "hou": "hou",
    "lafc": "lafc",
    "lag": "lag",
    "mia": "mia",
    "mim": "mim",
    "min": "min",
    "mtl": "mtl",
    "nyc": "nyc",
    "nyrb": "nyrb",
    "orl": "orl",
    "phi": "phi",
    "por": "por",
    "rsl": "rsl",
    "sea": "sea",
    "sj": "sj",
    "skc": "skc",
    "stl": "stl",
    "tor": "tor",
    "van": "van",
    # MLB.
    "ari": "ari",
    "az": "ari",
    "bal": "bal",
    "bos": "bos",
    "chc": "chc",
    "cws": "cws",
    "cle": "cle",
    "det": "det",
    "kc": "kc",
    "laa": "laa",
    "lad": "lad",
    "mia": "mia",
    "mil": "mil",
    "nym": "nym",
    "nyy": "nyy",
    "oak": "oak",
    "phi": "phi",
    "pit": "pit",
    "sd": "sd",
    "sdp": "sd",
    "sea": "sea",
    "sf": "sf",
    "stl": "stl",
    "tb": "tb",
    "tex": "tex",
    "wsh": "wsh",
    # NHL.
    "ana": "ana",
    "buf": "buf",
    "car": "car",
    "cbj": "cbj",
    "cgy": "cgy",
    "col": "col",
    "dal": "dal",
    "det": "det",
    "edm": "edm",
    "fla": "fla",
    "lak": "lak",
    "min": "min",
    "mtl": "mtl",
    "nj": "nj",
    "nsh": "nsh",
    "nyi": "nyi",
    "nyr": "nyr",
    "ott": "ott",
    "phi": "phi",
    "pit": "pit",
    "sea": "sea",
    "sj": "sj",
    "stl": "stl",
    "tbl": "tb",
    "tor": "tor",
    "uta": "uta",
    "vgk": "vgk",
    "wpg": "wpg",
    "wsh": "wsh",
    # NBA.
    "atl": "atl",
    "bkn": "bkn",
    "cha": "cha",
    "chi": "chi",
    "cle": "cle",
    "dal": "dal",
    "den": "den",
    "gs": "gsw",
    "gsw": "gsw",
    "hou": "hou",
    "ind": "ind",
    "lac": "lac",
    "lal": "lal",
    "mem": "mem",
    "mia": "mia",
    "mil": "mil",
    "min": "min",
    "nop": "nop",
    "ny": "nyk",
    "nyk": "nyk",
    "okc": "okc",
    "orl": "orl",
    "phi": "phi",
    "phx": "phx",
    "por": "por",
    "sac": "sac",
    "sas": "sas",
    "tor": "tor",
    "uta": "uta",
    "wsh": "wsh",
    # NFL.
    "ari": "ari",
    "atl": "atl",
    "bal": "bal",
    "buf": "buf",
    "car": "car",
    "chi": "chi",
    "cin": "cin",
    "cle": "cle",
    "dal": "dal",
    "den": "den",
    "det": "det",
    "gb": "gb",
    "hou": "hou",
    "ind": "ind",
    "jac": "jac",
    "jax": "jac",
    "kc": "kc",
    "lv": "lv",
    "lac": "lac",
    "lar": "lar",
    "mia": "mia",
    "min": "min",
    "ne": "ne",
    "no": "no",
    "nyg": "nyg",
    "nyj": "nyj",
    "phi": "phi",
    "pit": "pit",
    "sea": "sea",
    "sf": "sf",
    "tb": "tb",
    "ten": "ten",
    "wsh": "wsh",
    # European soccer aliases observed across Kalshi/Polymarket.
    "ars": "ars",
    "ast": "ast",
    "ata": "ata",
    "bar": "fcb",
    "bfc": "bol",
    "bmg": "bmg",
    "bol": "bol",
    "bor": "bor",
    "bre": "bre",
    "bvb": "bvb",
    "cag": "cag",
    "cfc": "cfc",
    "cry": "cry",
    "fcb": "fcb",
    "fio": "fio",
    "ful": "ful",
    "gen": "gen",
    "lev": "lev",
    "not": "not",
    "osa": "osa",
    "rbl": "rbl",
    "rom": "rom",
    "tot": "tot",
    "whu": "whu",
}


def normalize_entity_code(value: str | None) -> str:
    code = str(value or "").strip().lower()
    return TEAM_ALIASES.get(code, code)


def split_compound_code(value: str | None) -> tuple[str, str] | None:
    """Split Kalshi's concatenated participant code into two canonical codes."""
    text = str(value or "").strip().lower()
    if len(text) < 4:
        return None

    candidates: list[tuple[str, str]] = []
    known_codes = set(TEAM_ALIASES)
    for idx in range(2, len(text) - 1):
        left_raw = text[:idx]
        right_raw = text[idx:]
        left = normalize_entity_code(left_raw)
        right = normalize_entity_code(right_raw)
        if left_raw in known_codes and right_raw in known_codes:
            candidates.append((left, right))

    if not candidates:
        return None

    candidates.sort(key=lambda pair: (len(pair[0]) + len(pair[1]), pair[0], pair[1]))
    return candidates[0]


# Slug-to-code mapping for Polymarket championship markets.
# Maps team name slugs (e.g. "los-angeles-rams") to canonical team codes.
# Only covers teams that appear in championship futures markets.
_SLUG_TO_CODE: dict[str, str] = {
    # NFL
    "arizona-cardinals": "ari",
    "atlanta-falcons": "atl",
    "baltimore-ravens": "bal",
    "buffalo-bills": "buf",
    "carolina-panthers": "car",
    "chicago-bears": "chi",
    "cincinnati-bengals": "cin",
    "cleveland-browns": "cle",
    "dallas-cowboys": "dal",
    "denver-broncos": "den",
    "detroit-lions": "det",
    "green-bay-packers": "gb",
    "houston-texans": "hou",
    "indianapolis-colts": "ind",
    "jacksonville-jaguars": "jac",
    "kansas-city-chiefs": "kc",
    "las-vegas-raiders": "lv",
    "los-angeles-chargers": "lac",
    "los-angeles-rams": "lar",
    "miami-dolphins": "mia",
    "minnesota-vikings": "min",
    "new-england-patriots": "ne",
    "new-orleans-saints": "no",
    "new-york-giants": "nyg",
    "new-york-jets": "nyj",
    "philadelphia-eagles": "phi",
    "pittsburgh-steelers": "pit",
    "san-francisco-49ers": "sf",
    "seattle-seahawks": "sea",
    "tampa-bay-buccaneers": "tb",
    "tennessee-titans": "ten",
    "washington-commanders": "wsh",
    # NBA
    "atlanta-hawks": "atl",
    "boston-celtics": "bos",
    "brooklyn-nets": "bkn",
    "charlotte-hornets": "cha",
    "chicago-bulls": "chi",
    "cleveland-cavaliers": "cle",
    "dallas-mavericks": "dal",
    "denver-nuggets": "den",
    "detroit-pistons": "det",
    "golden-state-warriors": "gsw",
    "houston-rockets": "hou",
    "indiana-pacers": "ind",
    "los-angeles-clippers": "lac",
    "los-angeles-lakers": "lal",
    "memphis-grizzlies": "mem",
    "miami-heat": "mia",
    "milwaukee-bucks": "mil",
    "minnesota-timberwolves": "min",
    "new-orleans-pelicans": "nop",
    "new-york-knicks": "nyk",
    "oklahoma-city-thunder": "okc",
    "orlando-magic": "orl",
    "philadelphia-76ers": "phi",
    "phoenix-suns": "phx",
    "portland-trail-blazers": "por",
    "sacramento-kings": "sac",
    "san-antonio-spurs": "sas",
    "toronto-raptors": "tor",
    "utah-jazz": "uta",
    "washington-wizards": "wsh",
    # MLB
    "arizona-diamondbacks": "ari",
    "atlanta-braves": "atl",
    "baltimore-orioles": "bal",
    "boston-red-sox": "bos",
    "chicago-cubs": "chc",
    "chicago-white-sox": "cws",
    "cincinnati-reds": "cin",
    "cleveland-guardians": "cle",
    "colorado-rockies": "col",
    "detroit-tigers": "det",
    "houston-astros": "hou",
    "kansas-city-royals": "kc",
    "los-angeles-angels": "laa",
    "los-angeles-dodgers": "lad",
    "miami-marlins": "mia",
    "milwaukee-brewers": "mil",
    "minnesota-twins": "min",
    "new-york-mets": "nym",
    "new-york-yankees": "nyy",
    "oakland-athletics": "oak",
    "philadelphia-phillies": "phi",
    "pittsburgh-pirates": "pit",
    "san-diego-padres": "sd",
    "san-francisco-giants": "sf",
    "seattle-mariners": "sea",
    "st-louis-cardinals": "stl",
    "tampa-bay-rays": "tb",
    "texas-rangers": "tex",
    "toronto-blue-jays": "tor",
    "washington-nationals": "wsh",
    # NHL
    "anaheim-ducks": "ana",
    "boston-bruins": "bos",
    "buffalo-sabres": "buf",
    "calgary-flames": "cgy",
    "carolina-hurricanes": "car",
    "chicago-blackhawks": "chi",
    "colorado-avalanche": "col",
    "columbus-blue-jackets": "cbj",
    "dallas-stars": "dal",
    "detroit-red-wings": "det",
    "edmonton-oilers": "edm",
    "florida-panthers": "fla",
    "los-angeles-kings": "lak",
    "minnesota-wild": "min",
    "montreal-canadiens": "mtl",
    "nashville-predators": "nsh",
    "new-jersey-devils": "nj",
    "new-york-islanders": "nyi",
    "new-york-rangers": "nyr",
    "ottawa-senators": "ott",
    "philadelphia-flyers": "phi",
    "pittsburgh-penguins": "pit",
    "san-jose-sharks": "sj",
    "seattle-kraken": "sea",
    "st-louis-blues": "stl",
    "tampa-bay-lightning": "tb",
    "toronto-maple-leafs": "tor",
    "utah-hockey-club": "uta",
    "vegas-golden-knights": "vgk",
    "vancouver-canucks": "van",
    "washington-capitals": "wsh",
    "winnipeg-jets": "wpg",
    # MLS
    "atlanta-united": "atl",
    "austin-fc": "aus",
    "charlotte-fc": "cha",
    "chicago-fire": "chi",
    "fc-cincinnati": "cin",
    "colorado-rapids": "col",
    "columbus-crew": "clb",
    "fc-dallas": "dal",
    "dc-united": "dc",
    "houston-dynamo": "hou",
    "inter-miami": "mia",
    "la-galaxy": "lag",
    "lafc": "lafc",
    "minnesota-united": "min",
    "cf-montreal": "mtl",
    "nashville-sc": "nsh",
    "new-england-revolution": "ne",
    "new-york-city-fc": "nyc",
    "new-york-red-bulls": "nyrb",
    "orlando-city": "orl",
    "philadelphia-union": "phi",
    "portland-timbers": "por",
    "real-salt-lake": "rsl",
    "san-jose-earthquakes": "sj",
    "seattle-sounders": "sea",
    "sporting-kansas-city": "skc",
    "st-louis-city": "stl",
    "toronto-fc": "tor",
    "vancouver-whitecaps": "van",
    # NCAAF / College Football — only major programs likely to appear in futures
    "ohio-state": "ohst",
    "ohio-state-buckeyes": "ohst",
    "georgia": "uga",
    "georgia-bulldogs": "uga",
    "alabama": "ala",
    "alabama-crimson-tide": "ala",
    "michigan": "mich",
    "michigan-wolverines": "mich",
    "texas": "tex",
    "texas-longhorns": "tex",
    "oregon": "ore",
    "oregon-ducks": "ore",
    "penn-state": "psu",
    "penn-state-nittany-lions": "psu",
    "clemson": "clem",
    "clemson-tigers": "clem",
    "notre-dame": "nd",
    "notre-dame-fighting-irish": "nd",
    "lsu": "lsu",
    "lsu-tigers": "lsu",
    "usc": "usc",
    "usc-trojans": "usc",
    "tennessee": "tenn",
    "tennessee-volunteers": "tenn",
    "florida-state": "fsu",
    "florida-state-seminoles": "fsu",
    "oklahoma": "okla",
    "oklahoma-sooners": "okla",
    "miami-hurricanes": "canes",
    "colorado-buffaloes": "cubuf",
}


def resolve_slug_to_code(slug: str) -> str | None:
    """Resolve a Polymarket team-name slug to a canonical team code.

    Returns the code (lowercased) if found, otherwise None.
    Handles both full slugs ("los-angeles-rams") and bare codes ("lar").
    """
    slug = str(slug or "").strip().lower()
    if not slug:
        return None
    # Direct lookup in slug map
    if slug in _SLUG_TO_CODE:
        return _SLUG_TO_CODE[slug]
    # Maybe it's already a known team code
    if slug in TEAM_ALIASES:
        return TEAM_ALIASES[slug]
    return None


def canonical_pair(a: str, b: str) -> str:
    left = normalize_entity_code(a)
    right = normalize_entity_code(b)
    return "-".join(sorted((left, right)))
